version: '3'
services:
  db:
    image: mongo
    container_name: my-mongo
    volumes:
      - /mnt/data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: dynsight