export enum ProtocolList{
    MODBUS_SERIAL="MODBUS_SERIAL",
    MODBUS_IP="MODBUS_IP",
    BACNET_IP="BACNET_IP",
    LON_FT10="LON_FT10",
    LON_IP852="LON_IP852",
    LPB="LPB",
    LORAWAN_V1_0="LORAWAN_V1_0",
    MBUS="MBUS",
    WMBUS="WMBUS",
    KNX="KNX",
    BACNET_IP_GATEWAY="BACNET_IP_GATEWAY",
    MODBUS_IP_GATEWAY="MODBUS_IP_GATEWAY",
    PLUGIN_GATEWAY="PLUGIN_GATEWAY",
    MQTT_GATEWAY="MQTT_GATEWAY",
    VIRTUAL="VIRTUAL"
}